### ISSUE TITLE
Can't download  get from mvnrepository ,Prompt to deny access

### ISSUE THREAD

**Issue by BoneBee** [Esri/arcgis-runtime-samples-java#616]
Could not transfer artifact com.esri.arcgisruntime:arcgis-java:pom:100.9.0 from/to EsriArcGis (https://dl.bintray.com/esri/arcgis/): Access denied to: https://dl.bintray.com/esri/arcgis/com/esri/arcgisruntime/arcgis-java/100.9.0/arcgis-java-100.9.0.pom

**Comment by Rachael-E** [comment]
If you build your ArcGIS Runtime applications using Gradle or Maven build scripts which reference the Maven repository esri.bintray.com, you will need to update your scripts to reference a new Maven repository (see code snippet below from build.gradle for the url). Our new maven instance url is https://esri.jfrog.io/artifactory/arcgis. Please see https://www.esri.com/arcgis-blog/products/developers/announcements/announcement-to-developers-using-arcgis-runtime-sdks-for-android-and-java/ for more info. 
```
repositories {
    jcenter()
    maven {
        url 'https://esri.jfrog.io/artifactory/arcgis'
    }
}
```
